'use strict';
const assert=require('assert');const fs=require('fs');const os=require('os');const path=require('path');const net=require('net');const cp=require('child_process');
const t=fs.mkdtempSync(path.join(os.tmpdir(),'zeus-runner-'));const state=path.join(t,'state');const audit=path.join(t,'audit');fs.mkdirSync(state,0o770);fs.mkdirSync(audit,0o770);process.env.RUNNER_STATE_DIR=state;process.env.RUNNER_AUDIT_DIR=audit;const {handle}=require('./daemon');
const base={operation:'candidate_preflight',change_id:'V31-ISO-20260902-002',candidate_root:'/home/umbrel/umbrel/app-data/openclaw/data/zeus-v31-umbrel-candidates-20260902',expected_hash:'a'.repeat(64),job_id:'daemon-test',nonce:'n'.repeat(16),expires_at:new Date(Date.now()+60000).toISOString(),requested_by:'zeus-production',idempotency_key:'daemon-test-key-001'};
function c(n,f){try{f();console.log(`${n}: PASS`)}catch(e){console.log(`${n}: FAIL ${e.message}`);process.exitCode=1}}
c('state and audit write',()=>{const r=handle(JSON.stringify(base));assert.equal(r.status,'PASS');assert(fs.existsSync(path.join(state,'last-result.json')));assert(fs.existsSync(path.join(audit,'runner-audit.jsonl')))})
c('unknown operation denied',()=>assert.equal(handle(JSON.stringify({...base,operation:'docker_exec',job_id:'deny',idempotency_key:'daemon-deny-001'})).exit_code,64))
c('requester rejected',()=>assert.equal(handle(JSON.stringify({...base,job_id:'auth',requested_by:'not-zeus',idempotency_key:'daemon-auth-001'})).exit_code,64))
c('malformed rejected',()=>assert.equal(handle('{bad').exit_code,64))
c('docker operation unverified',()=>{const r=handle(JSON.stringify({...base,operation:'inspect_image',job_id:'docker',idempotency_key:'daemon-docker-001'}));assert.equal(r.status,'UNVERIFIED')});
(async()=>{const sock=path.join(t,'run','runner.sock');fs.mkdirSync(path.dirname(sock),0o770);const child=cp.spawn(process.execPath,['daemon.js'],{cwd:__dirname,env:{...process.env,RUNNER_SOCKET:sock},stdio:'ignore'});try{for(let i=0;i<50&&!fs.existsSync(sock);i++)await new Promise(r=>setTimeout(r,10));assert(fs.existsSync(sock));const reply=await new Promise((resolve,reject)=>{const c=net.createConnection(sock,()=>c.end(JSON.stringify({...base,job_id:'socket',idempotency_key:'daemon-socket-001'})+'\n'));let b='';c.on('data',x=>b+=x);c.on('end',()=>resolve(JSON.parse(b)));c.on('error',reject)});assert.equal(reply.status,'PASS');console.log('socket bind/connect: PASS');fs.chmodSync(sock,0o600);let denied;try{const u=cp.spawn(process.execPath,['-e',`const net=require("net");const c=net.createConnection(${JSON.stringify(sock)});c.on("connect",()=>process.exit(0));c.on("error",()=>process.exit(77))`],{uid:65534,gid:65534,stdio:'ignore'});denied=await new Promise(resolve=>{u.on('error',()=>resolve('UNVERIFIED'));u.on('exit',rc=>resolve(rc))})}catch(e){denied='UNVERIFIED'}if(denied==='UNVERIFIED')console.log('unauthorized client denied: UNVERIFIED (uid-switch EPERM)');else{assert.notEqual(denied,0);console.log('unauthorized client denied: PASS')}}finally{child.kill('SIGTERM');await new Promise(r=>child.on('exit',r));fs.rmSync(t,{recursive:true,force:true})}})().catch(e=>{console.error(e);process.exitCode=1});
