'use strict';
const assert=require('assert');const net=require('net');const fs=require('fs');const os=require('os');const path=require('path');const {probe}=require('./healthcheck');const {bindBuild,verifyContext}=require('./build-gate');
const id='sha256:'+'a'.repeat(64);function c(n,f){try{f();console.log(`${n}: PASS`)}catch(e){console.log(`${n}: FAIL ${e.message}`);process.exitCode=1}}
c('build success binds exact ID',()=>{const r=bindBuild({buildExit:0,iidText:id+'\n',inspectById:x=>({id:x,repo_digests:['repo@sha256:'+'b'.repeat(64)]})});assert.equal(r.status,'PASS');assert.equal(r.image_id,id);assert.equal(r.tag_identity,'REJECTED')});
c('build failure denied',()=>assert.equal(bindBuild({buildExit:1,iidText:id,inspectById:()=>{throw Error('must not call')}}).reason,'BUILD_FAILED'));
c('missing iid denied',()=>assert.equal(bindBuild({buildExit:0,inspectById:()=>({id})}).reason,'IIDFILE_MISSING'));
c('invalid iid denied',()=>assert.equal(bindBuild({buildExit:0,iidText:'sha256:old',inspectById:()=>({id})}).reason,'IID_INVALID'));
c('old tag cannot substitute',()=>assert.equal(bindBuild({buildExit:0,iidText:id,inspectById:()=>({id:'sha256:'+'c'.repeat(64)})}).reason,'IMAGE_ID_MISMATCH'));
c('changed context denied',()=>assert.equal(verifyContext({Dockerfile:'a',daemon:'b'},{Dockerfile:'a',daemon:'changed'}).reason,'CONTEXT_HASH_MISMATCH'));
c('short context denied',()=>assert.equal(verifyContext({Dockerfile:'a',daemon:'b'},{Dockerfile:'a'}).reason,'CONTEXT_HASH_MISMATCH'));
(async()=>{const t=fs.mkdtempSync(path.join(os.tmpdir(),'gate-'));const s=path.join(t,'sock');const server=net.createServer(cn=>{cn.on('data',()=>cn.end(JSON.stringify({status:'PASS',liveness:'PASS',mutation_gate:false})+'\n'))});await new Promise(r=>server.listen(s,r));let r=await probe(s,300);assert.equal(r.status,'PASS');console.log('liveness response: PASS');server.close();if(fs.existsSync(s))fs.unlinkSync(s);r=await probe(s,100);assert.equal(r.exit_code,111);console.log('stale socket no listener: PASS');const h=net.createServer(()=>{});const hs=path.join(t,'hang');await new Promise(x=>h.listen(hs,x));r=await probe(hs,50);assert.equal(r.exit_code,124);console.log('hung daemon timeout: PASS');h.close();const bad=net.createServer(cn=>{cn.on('data',()=>cn.end('{bad\n'))});const bs=path.join(t,'bad');await new Promise(x=>bad.listen(bs,x));r=await probe(bs,300);assert.equal(r.exit_code,65);console.log('invalid liveness response: PASS');bad.close();fs.rmSync(t,{recursive:true,force:true})})().catch(e=>{console.error(e);process.exitCode=1});
